### PR TITLE
feat(Resource-status/Details): implement panel resize

### PR DESCRIPTION
**Pull request by bdauria**
## Description

This allows the panel to be resized and reorganize the content. The width is also stored in the local storage.

resize-panel

**Fixes** # (issue)

## Type of change

- [x] New functionality (non-breaking change)

## Target serie

- [x] 21.04.x (master)

### CODE REVIEW

**Comment by Thebarda** [comment]
When expanding the side panel with services tab and graph mode selected, the refresh button seems too wide
refresh

**Review by Thebarda — COMMENTED** [review]
When expanding the side panel with services tab and graph mode selected, the refresh button seems too wide
refresh

**Comment by bdauria** [comment]
@Thebarda fixed

**Review by Thebarda — APPROVED** [review]
LGTM 👌
resize2

**Review by jdelpierre — APPROVED** [review]

**Pull request merged**
