### PR TITLE
enh(install): add Rockylinux support

### PR DESCRIPTION
**Pull request by lgcosta**
## Description

Add support to Rockylinux release

https://rockylinux.org/download

```
[root@rocky ~]# rpm -q --whatprovides /etc/redhat-release
rocky-release-8.4-26.el8.noarch
```

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Review by sc979 — DISMISSED** [review]
LGTM.
@Nohzoh what do you think ?

**Comment by UrBnW** [comment]
Not so much new there https://github.com/centreon/centreon/discussions/9317, is Debian support planned ? Any ETA ?
Many thx 👍

**Review by tuntoja — DISMISSED** [review]

**Review by Nohzoh — APPROVED** [review]

**Comment by srbala** [comment]
@lgcosta Can you add AlmaLinux support https://wiki.almalinux.org/Comparison.html

Website https://almalinux.org/

```sh 
[bala@almadev ~]$ rpm -q --whatprovides /etc/redhat-release
almalinux-release-8.4-2.el8.x86_64
```

Please let me know is separate PR requried for it.

**Comment by lgcosta** [comment]
> @lgcosta Can you add AlmaLinux support https://wiki.almalinux.org/Comparison.html
> 
> Website https://almalinux.org/
> 
> ```shell
> [bala@almadev ~]$ rpm -q --whatprovides /etc/redhat-release
> almalinux-release-8.4-2.el8.x86_64
> ```
> 
> Please let me know is separate PR requried for it.

Very good reference! Thanks

I need to validate the installation of packages and especially the part of compatibility with SELinux, done that, I believe you can enter this same PR.

**Comment by srbala** [comment]
> I need to validate the installation of packages and especially the part of compatibility with SELinux, done that, I believe you can enter this same PR.

@lgcosta I not clear, do you plan to update this PR after your SELinux validation  OR would like me to create a NEW PR similar to this one?

**Comment by lpinsivy** [comment]
We prefer to support Alma Linux instead of Rocky Linux

**Pull request closed without merging**
