### PR TITLE
enh(e2e): Add top counters tests to cypress

### PR DESCRIPTION
**Pull request by Thebarda**
## Description

This adds end to end cypress tests about top counter pollers and user profile

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

The CI should succeed.

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Comment by bdauria** [comment]
@Thebarda I don't think we should migrate the previous AT as they are, as they don't add that much value. I think it'd make more sense to add just one scenario to cover the top counter features (host, service status count).

The bottom line is: E2E tests should cover the most critical features as they cost a lot in terms of running time. The rest is typically covered by unit tests.

CC @jdelpierre

**Comment by Thebarda** [comment]
> @Thebarda I don't think we should migrate the previous AT as they are, as they don't add that much value. I think it'd make more sense to add just one scenario to cover the top counter features (host, service status count).
> 
> The bottom line is: E2E tests should cover the most critical features as they cost a lot in terms of running time. The rest is typically covered by unit tests.
> 
> CC @jdelpierre

Ok so we should remake the feature file

**Comment by Thebarda** [comment]
Should we close this PR ?

**Comment by jdelpierre** [comment]
indeed, it is necessary that one status (team and QA) the priority value to the use of the Top Counter to make E2E tests.  the rest would have to be done before that with other tests that are much cheaper and easier to maintain.

**Comment by Thebarda** [comment]
> indeed, it is necessary that one status (team and QA) the priority value to the use of the Top Counter to make E2E tests.  the rest would have to be done before that with other tests that are much cheaper and easier to maintain.

I want to point one thing: these tests are very easy to maintain and they are fast. 
We can let them temporally and let us the time to refactor them with the QA

**Pull request closed without merging**
