### PR TITLE
fix(clapi) Import fails on password type macros

### PR DESCRIPTION
**Pull request by callapa**
## Description
Added missing update scripts for previous versions (missed in the main fix #9338 )

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [x] 19.10.x
- [x] 20.04.x
- [x] 20.10.x
- [x] 21.04.x (master)

## Checklist

- [x] I have followed the **coding style guidelines** provided by Centreon
- [x] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Review by kduret — APPROVED** [review]

**Review by sc979 — COMMENTED** [review]
LGTM, but I don't understand how you'll be able to backport these on 19.10 and 20.04...
Looks like, you also need to correct the target versions in the description.
Why don't you create specific PR on the maintenance branches, instead of the master ?

**Comment by callapa** [comment]
> LGTM, but I don't understand how you'll be able to backport these on 19.10 and 20.04...
> Looks like, you also need to correct the target versions in the description.
> Why don't you create specific PR on the maintenance branches, instead of the master ?

As previously discussed with Kevin, the master must contain all the update scripts of all the targeted versions. The goal being that the update scripts are not lost as updates are made.

**Review by jeremyjaouen — APPROVED** [review]

**Comment by sc979** [comment]
> > LGTM, but I don't understand how you'll be able to backport these on 19.10 and 20.04...
> > Looks like, you also need to correct the target versions in the description.
> > Why don't you create specific PR on the maintenance branches, instead of the master ?
> 
> As previously discussed with Kevin, the master must contain all the update scripts of all the targeted versions. The goal being that the update scripts are not lost as updates are made.
> Subsequently, PRs will be added to include the update scripts in their respective versions.

But the same modifications are already present in the 20.10.3 upgrade script... IMHO, it seems overkill to check 3 times the same things when you upgrade from a 19.10.x

**Review by sc979 — APPROVED** [review]
A new PR seems to be required for the 19.10.x maintenance branch
I've added the 20.04.x version in the targets, as it will be cherry-pickable

**Pull request merged**
