### PR TITLE
Extend clapi

### PR DESCRIPTION
**Pull request by disaster37**
## Description

- Add getparam on some objects:
  - Command
  - HostGroup
  - ServiceGoup
  - Service
  - ServiceTemplate
- Allow `comment` on getparam from `Host` object
- Allow to show `Service` object with hostname and servicename filters (as parameters)
- Add actions to get, set, add, delete categories on `Service` object
- Add actions to get, set, add, delete service groups on `Service` object
- Add action to show host by address call `showbyaddress`

We need this change to develop Puppet Centreon provider: https://github.com/disaster37/puppet-hm_centreon

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 2.8.x
- [ ] 18.10.x
- [X] 19.04.x
- [X] 19.10.x
- [X] 20.04.x (master)

<h2> How this pull request can be tested ? </h2>

You can use clapi command to test all change:
```bash
./centreon -u admin -p admin -o HOST -a getparam -v 'test;comment'
./centreon -u admin -p admin -o SG -a getparam -v 'test;alias|comment|name|activate|geo_coords'
./centreon -u admin -p admin -o HG -a getparam -v 'test;alias|comment|name|activate|notes|notes_url|action_url|icon_image|map_icon_image|geo_coords'
./centreon -u admin -p admin -o CMD -a getparam -v 'test;name|line|type|graph|example|comment|activate|enable_shell'
./centreon -u admin -p admin -o SERVICE -a getparam -v 'test;test;comment|activate|description|template|is_volatile|check_period|check_command|check_command_arguments|max_check_attempts|normal_check_interval|retry_check_interval|active_checks_enabled|passive_checks_enabled|notifications_enabled|contact_additive_inheritance|cg_additive_inheritance|notification_interval|notification_period|notification_options|first_notification_delay|obsess_over_service|check_freshness|freshness_threshold|event_handler_enabled|flap_detection_enabled|retain_status_information|retain_nonstatus_information|event_handler|event_handler_arguments|notes|notes_url|action_url|icon_image|icon_image_alt'
./centreon -u admin -p admin -o STPL -a getparam -v 'test;test;comment|activate|description|template|is_volatile|check_period|check_command|check_command_arguments|max_check_attempts|normal_check_interval|retry_check_interval|active_checks_enabled|passive_checks_enabled|notifications_enabled|contact_additive_inheritance|cg_additive_inheritance|notification_interval|notification_period|notification_options|first_notification_delay|obsess_over_service|check_freshness|freshness_threshold|event_handler_enabled|flap_detection_enabled|retain_status_information|retain_nonstatus_information|event_handler|event_handler_arguments|notes|notes_url|action_url|icon_image|icon_image_alt'
./centreon -u admin -p admin -o SERVICE -a show -v 'test;test'
./centreon -u admin -p admin -o HOST -a showbyaddress -v 'localhost'
./centreon -u admin -p admin -o SERVICE -a getservicegroup -v 'test;test'
./centreon -u admin -p admin -o SERVICE -a addservicegroup -v 'test;test;SG1'
./centreon -u admin -p admin -o SERVICE -a setservicegroup -v 'test;test;SG1'
./centreon -u admin -p admin -o SERVICE -a delservicegroup -v 'test;test;SG1'
./centreon -u admin -p admin -o SERVICE -a getcategory -v 'test;test'
./centreon -u admin -p admin -o SERVICE -a addcategory -v 'test;test;cat1'
./centreon -u admin -p admin -o SERVICE -a setcategory -v 'test;test;cat1'
./centreon -u admin -p admin -o SERVICE -a delcategory -v 'test;test;cat1'
./centreon -u admin -p admin -o STPL -a getcategory -v 'test'
./centreon -u admin -p admin -o STPL -a addcategory -v 'test;cat1'
./centreon -u admin -p admin -o STPL -a setcategory -v 'test;cat1'
./centreon -u admin -p admin -o STPL -a delcategory -v 'test;cat1'
```

### CODE REVIEW

**Comment by lpinsivy** [comment]
Hi @disaster37 can you update the documentation too to add getparam?

**Comment by disaster37** [comment]
Hi,

Where is the doc files to update them ?

**Comment by lpinsivy** [comment]
Hi @disaster37 you can find the documentation here: https://github.com/centreon/centreon-documentation/blob/master/en/api/clapi.md.

Can you make a PR for this project?

**Comment by disaster37** [comment]
PR done: https://github.com/centreon/centreon-documentation/pull/167

**Comment by disaster37** [comment]
any news about it ?

**Comment by loiclau** [comment]
Hi @disaster37 can you rebase your branch on master?

**Review by jeremyjaouen — APPROVED** [review]

**Comment by disaster37** [comment]
I have rebase this PR on upstream/master

**Review by loiclau — APPROVED** [review]

**Comment by loiclau** [comment]
Hi, thanks for your contribution

**Pull request merged**
